# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection with Autoencoders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKYgrwW1BbCxeOcU-7lO2w31ebT7-_yO
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix

def load_data():
    # Kaggle Credit Card Fraud Detection dataset (https://www.kaggle.com/mlg-ulb/creditcardfraud)
    df = pd.read_csv('creditcard.csv')
    return df

def preprocess(df):
    X = df.drop('Class', axis=1)
    y = df['Class']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

    # Use only normal transactions for training autoencoder
    X_train = X_train[y_train == 0]

    return X_train, X_test, y_test

def build_autoencoder(input_dim):
    input_layer = Input(shape=(input_dim,))
    encoded = Dense(14, activation='relu')(input_layer)
    encoded = Dense(7, activation='relu')(encoded)
    decoded = Dense(14, activation='relu')(encoded)
    decoded = Dense(input_dim, activation='sigmoid')(decoded)

    autoencoder = Model(inputs=input_layer, outputs=decoded)
    autoencoder.compile(optimizer='adam', loss='mse')
    return autoencoder

def main():
    print("Loading data...")
    df = load_data()
    X_train, X_test, y_test = preprocess(df)
    autoencoder = build_autoencoder(X_train.shape[1])

    early_stop = EarlyStopping(monitor='val_loss', patience=3, verbose=1)
    autoencoder.fit(X_train, X_train, epochs=50, batch_size=256, shuffle=True, validation_split=0.2, callbacks=[early_stop])

    # Reconstruction error on test set
    X_test_pred = autoencoder.predict(X_test)
    mse = np.mean(np.power(X_test - X_test_pred, 2), axis=1)

    # Threshold for anomaly
    threshold = np.percentile(mse, 95)
    y_pred = (mse > threshold).astype(int)

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

if __name__ == "__main__":
    main()